# Cloud Build configuration for notes_api
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/notes-api:${_TAG}',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/notes-api:latest',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/notes-api:${_TAG}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/notes-api:latest'
    ]

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/notes-api:${_TAG}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/notes-api:latest'

# Build options
options:
  # Use higher CPU machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Set disk size for build
  diskSizeGb: 100
  # Enable logging
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build (default is 10 minutes)
timeout: '1200s'

# Substitutions (can be overridden when triggering build)
substitutions:
  _REGION: 'us-central1'
  _REPOSITORY: 'notes-api-repo'
  _TAG: 'manual-build'
  _BUILD_ID: 'manual-build'
