name: notes_api
description: A REST API for managing user notes with CRUD operations using Firestore.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.1
  dotenv: ^4.2.0
  uuid: ^4.3.3
  http: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
